// ═══════════════════════════════════════════════════════════════════════
//  QUESTION DATABASE
//  Generated by Claude from AppuntiCompNet.pdf, merged with questions
//  extracted from TSR, ALL_MERGED, reti_Quiz and CNTAS past-exam PDFs.
//  Update manually here, or via the "Import / update question DB" button.
// ═══════════════════════════════════════════════════════════════════════
const CHAPTER_ORDER = [
  "IPv4 Addressing and Routing",
  "IPv6",
  "IPv4 to IPv6 Transition",
  "Wireless and Cellular Networks",
  "Principles of Modern LAN Design and Operation",
  "Routing",
  "Multimedia Networking and Quality of Service",
  "Virtual Private Network",
  "The Optical Internet",
  "MPLS - Multi-Protocol Label Switching",
  "CDN - Content Delivery Network",
  "Pattern Analysis"
];
const DIFF_ORDER = ["easy", "medium", "hard"];
const DIFF_LABEL = { easy: "Easy", medium: "Medium", hard: "Hard" };
const LETTERS = ["A","B","C","D","E","F"];

// ═══════════════════════════════════════════════════════════════════════
//  FILTER STATE
// ═══════════════════════════════════════════════════════════════════════
let activeChapters   = new Set(CHAPTER_ORDER);
let activeDiffs      = new Set(DIFF_ORDER);
let activeSource     = "all"; // all | generated | imported

function buildFilterUI() {
  const chBox = document.getElementById('chapter-chips');
  chBox.innerHTML = CHAPTER_ORDER.map(c => {
    const count = DB.filter(q => q.chapter === c).length;
    if (count === 0) return '';
    return `<span class="chip active" data-chapter="${escapeAttr(c)}" onclick="toggleChapter('${escapeJs(c)}')">${c} <span style="opacity:.6">(${count})</span></span>`;
  }).join('');

  const dBox = document.getElementById('diff-chips');
  dBox.innerHTML = DIFF_ORDER.map(d =>
    `<span class="chip diff-${d} active" data-diff="${d}" onclick="toggleDiff('${d}')">${DIFF_LABEL[d]}</span>`
  ).join('');

  const sBox = document.getElementById('source-chips');
  const genCount = DB.filter(q => q.source === 'generated').length;
  const impCount = DB.filter(q => q.source === 'imported').length;
  sBox.innerHTML = `
    <span class="chip active" data-source="all" onclick="setSource('all')">All (${DB.length})</span>
    <span class="chip" data-source="generated" onclick="setSource('generated')"><span class="dot dot-gen" style="margin-right:5px"></span>Generated (${genCount})</span>
    <span class="chip" data-source="imported" onclick="setSource('imported')"><span class="dot dot-imp" style="margin-right:5px"></span>Past exams (${impCount})</span>
  `;
}

function escapeAttr(s) { return String(s).replace(/"/g, '&quot;'); }
function escapeJs(s) { return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'"); }

function toggleFilters() {
  document.getElementById('filters-head').classList.toggle('open');
  document.getElementById('filters-body').classList.toggle('open');
}

function toggleChapter(c) {
  if (activeChapters.has(c)) activeChapters.delete(c); else activeChapters.add(c);
  document.querySelector(`.chip[data-chapter="${CSS.escape(c)}"]`).classList.toggle('active');
  syncHomeCount();
}
function setAllChapters(on) {
  activeChapters = on ? new Set(CHAPTER_ORDER) : new Set();
  document.querySelectorAll('.chip[data-chapter]').forEach(el => el.classList.toggle('active', on));
  syncHomeCount();
}
function toggleDiff(d) {
  if (activeDiffs.has(d)) activeDiffs.delete(d); else activeDiffs.add(d);
  document.querySelector(`.chip[data-diff="${d}"]`).classList.toggle('active');
  syncHomeCount();
}
function setSource(s) {
  activeSource = s;
  document.querySelectorAll('.chip[data-source]').forEach(el => el.classList.toggle('active', el.dataset.source === s));
  syncHomeCount();
}

function getFilteredDB() {
  return DB.filter(q =>
    activeChapters.has(q.chapter) &&
    activeDiffs.has(q.difficulty) &&
    (activeSource === 'all' || q.source === activeSource)
  );
}

// ═══════════════════════════════════════════════════════════════════════
//  STATE
// ═══════════════════════════════════════════════════════════════════════
let quiz     = [];
let qIdx     = 0;
let score    = 0;
let wrong    = [];   // { q, userIdx }
let answered = false;
let userStats = { completed: new Set(), wrong: new Set() };


// ═══════════════════════════════════════════════════════════════════════
//  NAVIGATION
// ═══════════════════════════════════════════════════════════════════════
function show(id) {
  document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
  document.getElementById(id).classList.add('active');
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

function adjustCount(delta) {
  const inp = document.getElementById('quiz-count');
  const max = getFilteredDB().length || 1;
  const next = Math.min(Math.max(1, (parseInt(inp.value) || 1) + delta), max);
  inp.value = next;
}

function syncHomeCount() {
  const filtered = getFilteredDB();
  const n = filtered.length;
  const inp = document.getElementById('quiz-count');
  document.getElementById('home-total').textContent = n;
  inp.max = Math.max(n, 1);
  if (n === 0) { inp.value = 0; }
  else if (parseInt(inp.value) > n || !inp.value || parseInt(inp.value) < 1) { inp.value = Math.min(20, n); }
}

function goHome() {
  syncHomeCount();
  show('screen-home');
}

// ═══════════════════════════════════════════════════════════════════════
//  QUIZ
// ═══════════════════════════════════════════════════════════════════════
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function startQuiz() {
  const filtered = getFilteredDB();
  if (filtered.length === 0) { alert('No questions match the current filters. Adjust the filters and try again.'); return; }
  const raw   = parseInt(document.getElementById('quiz-count').value) || 15;
  const count = Math.min(Math.max(1, raw), filtered.length);
  document.getElementById('quiz-count').value = count;
  quiz     = shuffle(filtered).slice(0, count).map(q => {
    const newQ = { ...q, options: [...q.options] };
    const indices = newQ.options.map((_, i) => i);
    for (let i = indices.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [indices[i], indices[j]] = [indices[j], indices[i]];
    }
    newQ.options = indices.map(i => q.options[i]);
    newQ.correctIndex = indices.indexOf(q.correctIndex);
    return newQ;
  });
  qIdx     = 0;
  score    = 0;
  wrong    = [];
  answered = false;
  document.getElementById('quiz-drawer').classList.remove('open');
  show('screen-quiz');
  renderDrawer();
  renderQ();
}

function renderDrawer() {
  const grid = document.getElementById('drawer-grid');
  if (!grid) return;
  grid.innerHTML = quiz.map((q, i) => {
    let classes = 'drawer-sq';
    if (i === qIdx) classes += ' active';
    if (q.userAnswer !== undefined) {
      classes += (q.userAnswer === q.correctIndex) ? ' answered-ok' : ' answered-err';
    }
    return `<div class="${classes}" onclick="goToQuestion(${i})">${i + 1}</div>`;
  }).join('');
}

function toggleDrawer() {
  const d = document.getElementById('quiz-drawer');
  d.classList.toggle('open');
  const btn = d.querySelector('.drawer-toggle');
  btn.textContent = d.classList.contains('open') ? '▶' : '◀';
}

function goToQuestion(idx) {
  if (idx >= 0 && idx < quiz.length) {
    qIdx = idx;
    renderQ();
    renderDrawer();
  }
}

function renderQ() {
  const q     = quiz[qIdx];
  const total = quiz.length;
  const pct   = Math.round((qIdx / total) * 100);

  document.getElementById('q-counter').textContent  = `Question ${qIdx + 1} / ${total}`;
  document.getElementById('live-score').textContent  = `✓ ${score} correct`;

  document.getElementById('prog-fill').style.width   = `${pct}%`;
  document.getElementById('prog-label').textContent  = `${pct}%`;

  const diff = q.difficulty || 'medium';
  document.getElementById('q-section').innerHTML =
    `${q.chapter || ''} &nbsp;<span class="diff-badge diff-${diff}">${DIFF_LABEL[diff] || diff}</span>`;
  document.getElementById('q-topic').textContent = q.topic || '';
  const originEl = document.getElementById('q-origin');
  if (q.source === 'generated') {
    originEl.innerHTML = `<span class="dot dot-gen"></span> generated`;
  } else {
    originEl.innerHTML = `<span class="dot dot-imp"></span> ${q.sourceLabel ? 'exam · ' + q.sourceLabel : 'past exam'}`;
  }
  document.getElementById('q-label').textContent = `Question ${qIdx + 1}`;
  document.getElementById('q-text').textContent  = q.question;

  const optList = document.getElementById('opt-list');
  optList.innerHTML = q.options.map((opt, i) => `
    <button class="opt-btn" id="opt-${i}" onclick="answer(${i})">
      <span class="opt-letter">${LETTERS[i]}</span>
      <span class="opt-text">${escapeHtml(opt)}</span>
    </button>
  `).join('');

  document.getElementById('feedback-box').style.display = 'none';
  document.getElementById('feedback-box').innerHTML    = '';
  document.getElementById('exit-confirm').style.display = 'none';

  const btnPrev = document.getElementById('btn-prev');
  const btnNext = document.getElementById('btn-next');
  if (btnPrev) btnPrev.style.visibility = (qIdx > 0) ? 'visible' : 'hidden';
  if (btnNext) {
    btnNext.style.display = 'block';
    if (qIdx + 1 < quiz.length) {
      btnNext.textContent = 'Next  →';
      btnNext.onclick = nextQuestion;
    } else {
      btnNext.textContent = 'See results  →';
      btnNext.onclick = showResults;
    }
  }

  answered = false;

  // Restore state if already answered
  if (q.userAnswer !== undefined) {
    answered = true;
    q.options.forEach((opt, i) => {
      const btn = document.getElementById(`opt-${i}`);
      btn.disabled = true;
      if (i === q.correctIndex) btn.classList.add('correct');
      else if (i === q.userAnswer) btn.classList.add('wrong-selected');
      else btn.classList.add('dimmed');
    });

    const isCorrect = (q.userAnswer === q.correctIndex);
    const fb  = document.getElementById('feedback-box');
    const cls = isCorrect ? 'correct' : 'wrong';
    fb.innerHTML = `
      <div class="feedback feedback-${cls}">
        <div class="feedback-verdict">
          ${isCorrect ? '✅ Correct!' : '❌ Wrong!'}
        </div>
        ${!isCorrect ? `<div class="feedback-correct-ans">Correct answer: <strong>${LETTERS[q.correctIndex]}) ${escapeHtml(q.options[q.correctIndex])}</strong></div>` : ''}
        <div class="feedback-exp"><strong>Explanation &nbsp;—</strong> ${escapeHtml(q.explanation)}</div>
      </div>`;
    fb.style.display = 'block';
  }
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function answer(choiceIdx) {
  if (answered) return;
  answered = true;

  const q         = quiz[qIdx];
  const isCorrect = choiceIdx === q.correctIndex;

  q.userAnswer = choiceIdx;
  
  if (q.id) {
    userStats.completed.add(q.id);
    if (isCorrect) {
      userStats.wrong.delete(q.id);
    } else {
      userStats.wrong.add(q.id);
    }
  }

  if (isCorrect) {
    score++;
  } else {
    wrong.push({ q, userIdx: choiceIdx });
  }

  document.getElementById('live-score').textContent = `✓ ${score} correct`;

  q.options.forEach((opt, i) => {
    const btn = document.getElementById(`opt-${i}`);
    btn.disabled = true;
    if (i === q.correctIndex) btn.classList.add('correct');
    else if (i === choiceIdx) btn.classList.add('wrong-selected');
    else btn.classList.add('dimmed');
  });

  const fb  = document.getElementById('feedback-box');
  const cls = isCorrect ? 'correct' : 'wrong';
  fb.innerHTML = `
    <div class="feedback feedback-${cls}">
      <div class="feedback-verdict">
        ${isCorrect ? '✅ Correct!' : '❌ Wrong!'}
      </div>
      ${!isCorrect ? `<div class="feedback-correct-ans">Correct answer: <strong>${LETTERS[q.correctIndex]}) ${escapeHtml(q.options[q.correctIndex])}</strong></div>` : ''}
      <div class="feedback-exp"><strong>Explanation &nbsp;—</strong> ${escapeHtml(q.explanation)}</div>
    </div>`;
  fb.style.display = 'block';

  renderDrawer();
}

function nextQuestion() {
  if (qIdx + 1 < quiz.length) {
    qIdx++;
    renderQ();
    renderDrawer();
  }
}

function prevQuestion() {
  if (qIdx > 0) {
    qIdx--;
    renderQ();
    renderDrawer();
  }
}

// ═══════════════════════════════════════════════════════════════════════
//  EARLY EXIT
// ═══════════════════════════════════════════════════════════════════════
function toggleExitConfirm() {
  const box = document.getElementById('exit-confirm');
  box.style.display = box.style.display === 'block' ? 'none' : 'block';
}

function exitQuiz() {
  showResults();
}

// ═══════════════════════════════════════════════════════════════════════
//  RESULTS
// ═══════════════════════════════════════════════════════════════════════
function showResults() {
  show('screen-results');

  const total = score + wrong.length;
  const pct   = total === 0 ? 0 : Math.round((score / total) * 100);

  document.getElementById('res-score').textContent = score;
  document.getElementById('res-total').textContent = total;
  document.getElementById('res-ok').textContent    = score;
  document.getElementById('res-err').textContent   = wrong.length;

  const earlyExit = total < quiz.length;
  let title, sub;
  if (total === 0) {
    title = '🤷 No answers';
    sub   = 'You ended the quiz without answering any question.';
  } else if (earlyExit) {
    title = '⏹ Quiz ended early';
    sub   = `You answered ${total} question${total !== 1 ? 's' : ''} out of ${quiz.length} — ${pct}% correct.`;
  } else if (pct === 100)    { title = '🏆 Perfect!';        sub = 'You answered every question correctly!'; }
  else if (pct >= 80)        { title = '🌟 Great!';           sub = `${pct}% correct — almost perfect!`; }
  else if (pct >= 60)        { title = '👍 Good';             sub = `${pct}% correct — you can improve!`; }
  else if (pct >= 40)        { title = '📚 Needs review';     sub = `${pct}% correct — review the wrong answers.`; }
  else                       { title = '💪 Keep going!';      sub = `${pct}% correct — revisit the theory.`; }

  document.getElementById('res-title').textContent = title;
  document.getElementById('res-sub').textContent   = sub;

  const btnR = document.getElementById('btn-review');
  if (wrong.length === 0) {
    btnR.style.display = 'none';
  } else {
    btnR.style.display  = 'block';
    btnR.textContent = `🔍  Review ${wrong.length} wrong answer${wrong.length !== 1 ? 's' : ''}`;
  }
}

// ═══════════════════════════════════════════════════════════════════════
//  REVIEW
// ═══════════════════════════════════════════════════════════════════════
function startReview() {
  show('screen-review');
  document.getElementById('review-sub').textContent =
    `${wrong.length} question${wrong.length !== 1 ? 's' : ''} to review`;

  const list = document.getElementById('review-list');
  list.innerHTML = '';

  wrong.forEach((item, i) => {
    const q = item.q;
    const div = document.createElement('div');
    div.className = 'review-item';
    div.style.animationDelay = `${i * 0.05}s`;
    const originHtml = q.source === 'generated'
      ? `<span class="dot dot-gen"></span> generated`
      : `<span class="dot dot-imp"></span> ${q.sourceLabel || 'past exam'}`;
    div.innerHTML = `
      <div class="ri-tag">
        Mistake ${i + 1}
        <span class="ri-section">· ${q.chapter || ''}${q.topic ? ' — ' + q.topic : ''}</span>
        <span class="ri-section">· ${originHtml}</span>
      </div>
      <div class="ri-q">${escapeHtml(q.question)}</div>
      <div class="ri-badges">
        <span class="badge badge-wrong">✗ You answered: ${LETTERS[item.userIdx]}) ${escapeHtml(q.options[item.userIdx])}</span>
        <span class="badge badge-correct">✓ Correct: ${LETTERS[q.correctIndex]}) ${escapeHtml(q.options[q.correctIndex])}</span>
      </div>
      <div class="ri-exp"><strong>Explanation</strong><br>${escapeHtml(q.explanation)}</div>
    `;
    list.appendChild(div);
  });
}

// ═══════════════════════════════════════════════════════════════════════
//  PROFILE & CUSTOM QUIZZES
// ═══════════════════════════════════════════════════════════════════════
function showProfile() {
  document.getElementById('prof-wrong-count').textContent = userStats.wrong.size;
  const btnWrong = document.getElementById('btn-start-wrong');
  btnWrong.style.display = userStats.wrong.size > 0 ? 'inline-block' : 'none';

  const chContainer = document.getElementById('prof-chapters');
  chContainer.innerHTML = '';

  CHAPTER_ORDER.forEach(c => {
    const total = DB.filter(q => q.chapter === c).length;
    if (total === 0) return;
    
    const completed = DB.filter(q => q.chapter === c && userStats.completed.has(q.id)).length;
    const pct = Math.round((completed / total) * 100) || 0;
    const unseen = DB.filter(q => q.chapter === c && !userStats.completed.has(q.id));

    const div = document.createElement('div');
    div.className = 'ch-card';
    div.innerHTML = `
      <div class="ch-card-header">
        <div class="ch-title">${c}</div>
        <div class="ch-nums">${completed} / ${total}</div>
      </div>
      <div class="ch-prog-wrap">
        <div class="ch-prog-fill" style="width: ${pct}%"></div>
      </div>
      <div class="ch-card-actions">
        <button class="btn btn-secondary" style="padding: 6px 12px; font-size: 0.8rem; width: auto;" 
          ${unseen.length === 0 ? 'disabled' : ''} 
          onclick="startCustomQuiz('${escapeJs(c)}', 20)">
          Fai ${Math.min(20, unseen.length)} nuove domande
        </button>
      </div>
    `;
    chContainer.appendChild(div);
  });

  show('screen-profile');
}

function startCustomQuiz(chapter, maxCount) {
  let questions;
  if (chapter === 'WRONG') {
    questions = DB.filter(q => userStats.wrong.has(q.id));
  } else {
    questions = DB.filter(q => q.chapter === chapter && !userStats.completed.has(q.id));
  }
  
  if (questions.length === 0) return;
  
  const count = Math.min(questions.length, maxCount || 20);
  quiz = shuffle(questions).slice(0, count).map(q => {
    const newQ = { ...q, options: [...q.options] };
    const indices = newQ.options.map((_, i) => i);
    for (let i = indices.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [indices[i], indices[j]] = [indices[j], indices[i]];
    }
    newQ.options = indices.map(i => q.options[i]);
    newQ.correctIndex = indices.indexOf(q.correctIndex);
    return newQ;
  });
  
  qIdx = 0;
  score = 0;
  wrong = [];
  answered = false;
  document.getElementById('quiz-drawer').classList.remove('open');
  show('screen-quiz');
  renderDrawer();
  renderQ();
}

function startWrongQuiz() {
  startCustomQuiz('WRONG', 50);
}

// ═══════════════════════════════════════════════════════════════════════
// (Import modal removed)

// ═══════════════════════════════════════════════════════════════════════
//  PRINT / PDF
// ═══════════════════════════════════════════════════════════════════════
function stampaPDF() {
  const filtered = getFilteredDB();
  if (filtered.length === 0) { alert('No questions match the current filters.'); return; }

  const sections = {};
  filtered.forEach((q, i) => {
    const s = q.chapter || 'Uncategorized';
    if (!sections[s]) sections[s] = [];
    sections[s].push({ ...q, num: i + 1 });
  });

  let body = '';
  for (const [sec, qs] of Object.entries(sections)) {
    body += `<div class="section-title">${sec}</div>`;
    qs.forEach(q => {
      const originBadge = q.source === 'generated'
        ? '<span class="badge gen">generated</span>'
        : `<span class="badge imp">${q.sourceLabel || 'past exam'}</span>`;
      const optsHtml = q.options.map((o, i) => `
        <div class="opt-line ${i === q.correctIndex ? 'correct' : ''}">${LETTERS[i]}) ${o}${i === q.correctIndex ? ' ✓' : ''}</div>
      `).join('');
      body += `
        <div class="q-card">
          <div class="q-header">
            <span class="q-num">${q.num}.</span>
            <span class="q-text">${q.question} ${originBadge} <span class="badge diff">${DIFF_LABEL[q.difficulty] || q.difficulty}</span></span>
          </div>
          <div class="opts">${optsHtml}</div>
          <div class="q-explanation">${q.explanation}</div>
        </div>`;
    });
  }

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>Computer Network Technologies and Services — Quiz</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Georgia,serif;font-size:11pt;color:#111;background:#fff}
.cover{text-align:center;padding:40px 32px 28px;border-bottom:2px solid #111;margin-bottom:28px}
.cover h1{font-size:20pt;font-weight:bold;margin-bottom:6px}
.cover p{font-size:11pt;color:#555}
.section-title{font-size:12pt;font-weight:bold;background:#f0f4ff;border-left:4px solid #2563eb;padding:7px 12px;margin:26px 0 12px;page-break-after:avoid}
.q-card{border:1px solid #ddd;border-radius:5px;padding:12px 14px;margin-bottom:11px;page-break-inside:avoid}
.q-header{display:flex;align-items:flex-start;gap:8px;margin-bottom:7px}
.q-num{font-size:9pt;color:#888;min-width:26px;padding-top:2px;font-family:sans-serif}
.q-text{font-size:11pt;flex:1;line-height:1.5}
.badge{display:inline-block;font-family:sans-serif;font-size:8pt;font-weight:bold;padding:2px 7px;border-radius:4px;margin-left:6px;white-space:nowrap}
.badge.gen{background:#e0e7ff;color:#4338ca;border:1px solid #c7d2fe}
.badge.imp{background:#fef3c7;color:#92400e;border:1px solid #fde68a}
.badge.diff{background:#f1f5f9;color:#334155;border:1px solid #e2e8f0}
.opts{font-family:sans-serif;font-size:9.5pt;margin:8px 0;color:#333}
.opt-line{padding:2px 0}
.opt-line.correct{color:#15803d;font-weight:bold}
.q-explanation{font-size:9.5pt;color:#444;line-height:1.5;border-top:1px dashed #ccc;margin-top:7px;padding-top:7px;font-style:italic}
.footer{text-align:center;margin-top:36px;font-size:9pt;color:#999;font-family:sans-serif}
@media print{@page{margin:1.8cm 1.5cm}body{font-size:10pt}.section-title{margin:18px 0 9px}}
</style></head><body>
<div class="cover">
  <h1>Computer Network Technologies and Services — Quiz</h1>
  <p>${filtered.length} questions &nbsp;·&nbsp; full set with answers and explanations (current filters)</p>
</div>
${body}
<div class="footer">Quiz CNTaS &mdash; ${filtered.length} questions total</div>
<script>window.onload=function(){window.print()}<\/script>
</body></html>`;

  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
}

// ═══════════════════════════════════════════════════════════════════════
//  INIT
// ═══════════════════════════════════════════════════════════════════════
buildFilterUI();
syncHomeCount();

